source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'
# Use mysql as the database for Active Record
gem 'mysql2'
gem 'sass-rails', '~> 4.0.0'
gem 'bootstrap-sass', '2.3.2.0'
gem 'will_paginate', '3.0.4'
gem 'bootstrap-will_paginate', '0.0.9'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'turbolinks'
gem 'devise'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'
gem 'owlcarousel-rails'
gem 'ckeditor', '4.0.4'
gem "jquery-rails"
gem 'twitter-bootstrap-rails'
gem 'carousel'
gem 'carrierwave'
gem 'mini_magick', :git => 'git://github.com/probablycorey/mini_magick.git'
gem 'paperclip', '~> 3.0'
gem 'rmagick', '2.13.2', :git=>'http://github.com/rmagick/rmagick.git'
gem "jquery-fileupload-rails" 
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'
gem 'money-rails'
group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use Andle inctiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'
group :development do
  gem 'rails_layout', github: 'RailsApps/rails_layout'
end
# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


